services:
  database:
    container_name: database
    image: mariadb:10.6.18
    environment:
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: dreaminaction
    ports:
      - '3306:3306'
