version: '3.1'

services:
  database:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dreaminaction
    ports:
      - '5432:5432'
